export const EventType = Object.freeze({
  // Identity & clan
  PLAYER_CREATED: 'PLAYER_CREATED',
  PERSONALITY_TEST_COMPLETED: 'PERSONALITY_TEST_COMPLETED',
  CLAN_ASSIGNED: 'CLAN_ASSIGNED',

  // Location & transit
  STATION_DETECTED: 'STATION_DETECTED',
  METRO_SESSION_STARTED: 'METRO_SESSION_STARTED',
  METRO_SESSION_CONFIRMED: 'METRO_SESSION_CONFIRMED',
  METRO_SESSION_REJECTED: 'METRO_SESSION_REJECTED',

  // Scoring
  SCORE_GRANTED: 'SCORE_GRANTED',

  // Weekly cycle
  WEEKLY_RESULT: 'WEEKLY_RESULT',

  // Invasions
  INVASION_DECLARED: 'INVASION_DECLARED',
  INVASION_RESULT: 'INVASION_RESULT',
  CLAN_MEMBERSHIP_CHANGED: 'CLAN_MEMBERSHIP_CHANGED',

  // Random modifiers
  RANDOM_EVENT_TRIGGERED: 'RANDOM_EVENT_TRIGGERED'
})
